// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.account.setPrimaryEmail

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempAccountSetPrimaryEmailNSID = "org.tangled.temp.account.setPrimaryEmail"
)

// TempAccountSetPrimaryEmail_Input is the input argument to a org.tangled.temp.account.setPrimaryEmail call.
type TempAccountSetPrimaryEmail_Input struct {
	// email: Email address to promote to primary.
	Email string `json:"email" cborgen:"email"`
}

// TempAccountSetPrimaryEmail calls the XRPC method "org.tangled.temp.account.setPrimaryEmail".
func TempAccountSetPrimaryEmail(ctx context.Context, c util.LexClient, input *TempAccountSetPrimaryEmail_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "org.tangled.temp.account.setPrimaryEmail", nil, input, nil); err != nil {
		return err
	}

	return nil
}
