// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.account.subscribeNewsletter

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempAccountSubscribeNewsletterNSID = "org.tangled.temp.account.subscribeNewsletter"
)

// TempAccountSubscribeNewsletter calls the XRPC method "org.tangled.temp.account.subscribeNewsletter".
func TempAccountSubscribeNewsletter(ctx context.Context, c util.LexClient) error {
	if err := c.LexDo(ctx, util.Procedure, "", "org.tangled.temp.account.subscribeNewsletter", nil, nil, nil); err != nil {
		return err
	}

	return nil
}
