// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.account.deleteEmail

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempAccountDeleteEmailNSID = "org.tangled.temp.account.deleteEmail"
)

// TempAccountDeleteEmail_Input is the input argument to a org.tangled.temp.account.deleteEmail call.
type TempAccountDeleteEmail_Input struct {
	// email: Email address to remove.
	Email string `json:"email" cborgen:"email"`
}

// TempAccountDeleteEmail calls the XRPC method "org.tangled.temp.account.deleteEmail".
func TempAccountDeleteEmail(ctx context.Context, c util.LexClient, input *TempAccountDeleteEmail_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "org.tangled.temp.account.deleteEmail", nil, input, nil); err != nil {
		return err
	}

	return nil
}
