// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.account.beginSignup

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempAccountBeginSignupNSID = "org.tangled.temp.account.beginSignup"
)

// TempAccountBeginSignup_Input is the input argument to a org.tangled.temp.account.beginSignup call.
type TempAccountBeginSignup_Input struct {
	// email: Email address for the new account.
	Email string `json:"email" cborgen:"email"`
	// turnstileToken: Cloudflare Turnstile challenge response token.
	TurnstileToken string `json:"turnstileToken" cborgen:"turnstileToken"`
}

// TempAccountBeginSignup calls the XRPC method "org.tangled.temp.account.beginSignup".
func TempAccountBeginSignup(ctx context.Context, c util.LexClient, input *TempAccountBeginSignup_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "org.tangled.temp.account.beginSignup", nil, input, nil); err != nil {
		return err
	}

	return nil
}
