// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.account.completeSignup

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempAccountCompleteSignupNSID = "org.tangled.temp.account.completeSignup"
)

// TempAccountCompleteSignup_Input is the input argument to a org.tangled.temp.account.completeSignup call.
type TempAccountCompleteSignup_Input struct {
	// code: Verification code from the signup email.
	Code string `json:"code" cborgen:"code"`
	// password: Password for the new account.
	Password string `json:"password" cborgen:"password"`
	// username: Desired username; the assigned handle is <username>.<pds domain>.
	Username string `json:"username" cborgen:"username"`
}

// TempAccountCompleteSignup_Output is the output of a org.tangled.temp.account.completeSignup call.
type TempAccountCompleteSignup_Output struct {
	// did: DID of the newly provisioned account.
	Did string `json:"did" cborgen:"did"`
	// handle: The assigned handle, <username>.<pds domain>.
	Handle string `json:"handle" cborgen:"handle"`
}

// TempAccountCompleteSignup calls the XRPC method "org.tangled.temp.account.completeSignup".
func TempAccountCompleteSignup(ctx context.Context, c util.LexClient, input *TempAccountCompleteSignup_Input) (*TempAccountCompleteSignup_Output, error) {
	var out TempAccountCompleteSignup_Output
	if err := c.LexDo(ctx, util.Procedure, "application/json", "org.tangled.temp.account.completeSignup", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
