// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.account.dismissNewsletter

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempAccountDismissNewsletterNSID = "org.tangled.temp.account.dismissNewsletter"
)

// TempAccountDismissNewsletter calls the XRPC method "org.tangled.temp.account.dismissNewsletter".
func TempAccountDismissNewsletter(ctx context.Context, c util.LexClient) error {
	if err := c.LexDo(ctx, util.Procedure, "", "org.tangled.temp.account.dismissNewsletter", nil, nil, nil); err != nil {
		return err
	}

	return nil
}
