// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.actor.profile

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	ActorProfileNSID = "sh.tangled.actor.profile"
)

func init() {
	util.RegisterType("sh.tangled.actor.profile", &ActorProfile{})
} //
// RECORDTYPE: ActorProfile
type ActorProfile struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.actor.profile" cborgen:"$type,const=sh.tangled.actor.profile"`
	// avatar: Small image to be displayed next to posts from account. AKA, 'profile picture'
	Avatar *util.LexBlob `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	// bluesky: Include link to this account on Bluesky.
	Bluesky bool `json:"bluesky" cborgen:"bluesky"`
	// description: Free-form profile description text.
	Description *string  `json:"description,omitempty" cborgen:"description,omitempty"`
	Links       []string `json:"links,omitempty" cborgen:"links,omitempty"`
	// location: Free-form location text.
	Location *string `json:"location,omitempty" cborgen:"location,omitempty"`
	// pinnedRepositories: Any ATURI, it is up to appviews to validate these fields.
	PinnedRepositories []string `json:"pinnedRepositories,omitempty" cborgen:"pinnedRepositories,omitempty"`
	// preferredHandle: A handle the user prefers to be displayed as.
	PreferredHandle *string `json:"preferredHandle,omitempty" cborgen:"preferredHandle,omitempty"`
	// pronouns: Preferred gender pronouns.
	Pronouns *string  `json:"pronouns,omitempty" cborgen:"pronouns,omitempty"`
	Stats    []string `json:"stats,omitempty" cborgen:"stats,omitempty"`
}
