// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.ci.getPipeline

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	CiGetPipelineNSID = "sh.tangled.ci.getPipeline"
)

// CiGetPipeline calls the XRPC method "sh.tangled.ci.getPipeline".
//
// pipeline: Spindle-local pipeline id
func CiGetPipeline(ctx context.Context, c util.LexClient, pipeline string) (*CiDefs_Pipeline, error) {
	var out CiDefs_Pipeline

	params := map[string]interface{}{}
	params["pipeline"] = pipeline
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.ci.getPipeline", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
