// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.ci.subscribePipelineLogs

const (
	CiSubscribePipelineLogsNSID = "sh.tangled.ci.subscribePipelineLogs"
)

// CiSubscribePipelineLogs_Control is a "control" in the sh.tangled.ci.subscribePipelineLogs schema.
type CiSubscribePipelineLogs_Control struct {
	// command: Step command
	Command *string `json:"command,omitempty" cborgen:"command,omitempty"`
	Content string  `json:"content" cborgen:"content"`
	// kind: Step kind
	Kind *string `json:"kind,omitempty" cborgen:"kind,omitempty"`
	// status: Step status
	Status *string `json:"status,omitempty" cborgen:"status,omitempty"`
	// step: Step ID
	Step int64  `json:"step" cborgen:"step"`
	Time string `json:"time" cborgen:"time"`
	// workflow: workflow name
	Workflow string `json:"workflow" cborgen:"workflow"`
}

// CiSubscribePipelineLogs_Data is a "data" in the sh.tangled.ci.subscribePipelineLogs schema.
type CiSubscribePipelineLogs_Data struct {
	Content string `json:"content" cborgen:"content"`
	// step: Step ID
	Step   int64  `json:"step" cborgen:"step"`
	Stream string `json:"stream" cborgen:"stream"`
	Time   string `json:"time" cborgen:"time"`
	// workflow: workflow name
	Workflow string `json:"workflow" cborgen:"workflow"`
}
