// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.ci.trigger

const ()

// CiTrigger_Manual is a "manual" in the sh.tangled.ci.trigger schema.
//
// RECORDTYPE: CiTrigger_Manual
type CiTrigger_Manual struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.ci.trigger#manual" cborgen:"$type,const=sh.tangled.ci.trigger#manual"`
}

// CiTrigger_PullRequest is a "pullRequest" in the sh.tangled.ci.trigger schema.
//
// TODO: reference PR record with strongRef instead of embedding raw values
//
// RECORDTYPE: CiTrigger_PullRequest
type CiTrigger_PullRequest struct {
	LexiconTypeID string  `json:"$type,const=sh.tangled.ci.trigger#pullRequest" cborgen:"$type,const=sh.tangled.ci.trigger#pullRequest"`
	Action        string  `json:"action" cborgen:"action"`
	SourceBranch  *string `json:"sourceBranch,omitempty" cborgen:"sourceBranch,omitempty"`
	SourceSha     string  `json:"sourceSha" cborgen:"sourceSha"`
	TargetBranch  string  `json:"targetBranch" cborgen:"targetBranch"`
}

// CiTrigger_Push is a "push" in the sh.tangled.ci.trigger schema.
//
// RECORDTYPE: CiTrigger_Push
type CiTrigger_Push struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.ci.trigger#push" cborgen:"$type,const=sh.tangled.ci.trigger#push"`
	NewSha        string `json:"newSha" cborgen:"newSha"`
	OldSha        string `json:"oldSha" cborgen:"oldSha"`
	Ref           string `json:"ref" cborgen:"ref"`
}
