// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.star

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedStarNSID = "sh.tangled.feed.star"
)

func init() {
	util.RegisterType("sh.tangled.feed.star", &FeedStar{})
} //
// RECORDTYPE: FeedStar
type FeedStar struct {
	LexiconTypeID string  `json:"$type,const=sh.tangled.feed.star" cborgen:"$type,const=sh.tangled.feed.star"`
	CreatedAt     string  `json:"createdAt" cborgen:"createdAt"`
	Subject       *string `json:"subject,omitempty" cborgen:"subject,omitempty"`
	SubjectDid    *string `json:"subjectDid,omitempty" cborgen:"subjectDid,omitempty"`
}
