// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.countReactions

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedCountReactionsNSID = "sh.tangled.feed.countReactions"
)

// FeedCountReactions_Output is the output of a sh.tangled.feed.countReactions call.
type FeedCountReactions_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// FeedCountReactions calls the XRPC method "sh.tangled.feed.countReactions".
//
// subject: Record AT-URI the reactions target.
func FeedCountReactions(ctx context.Context, c util.LexClient, subject string) (*FeedCountReactions_Output, error) {
	var out FeedCountReactions_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.feed.countReactions", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
