// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.countStarsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedCountStarsByNSID = "sh.tangled.feed.countStarsBy"
)

// FeedCountStarsBy_Output is the output of a sh.tangled.feed.countStarsBy call.
type FeedCountStarsBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// FeedCountStarsBy calls the XRPC method "sh.tangled.feed.countStarsBy".
//
// subject: Actor DID whose star authorings to list.
func FeedCountStarsBy(ctx context.Context, c util.LexClient, subject string) (*FeedCountStarsBy_Output, error) {
	var out FeedCountStarsBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.feed.countStarsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
