// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.listComments

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedListCommentsNSID = "sh.tangled.feed.listComments"
)

// FeedListComments_ListItem is a "listItem" in the sh.tangled.feed.listComments schema.
type FeedListComments_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.feed.comment record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// FeedListComments_Output is the output of a sh.tangled.feed.listComments call.
type FeedListComments_Output struct {
	Cursor *string                      `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*FeedListComments_ListItem `json:"items" cborgen:"items"`
}

// FeedListComments calls the XRPC method "sh.tangled.feed.listComments".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Record AT-URI the comments attach to.
func FeedListComments(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*FeedListComments_Output, error) {
	var out FeedListComments_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.feed.listComments", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
