// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.listReactionsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedListReactionsByNSID = "sh.tangled.feed.listReactionsBy"
)

// FeedListReactionsBy_Output is the output of a sh.tangled.feed.listReactionsBy call.
type FeedListReactionsBy_Output struct {
	Cursor *string                       `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*FeedListReactions_ListItem `json:"items" cborgen:"items"`
}

// FeedListReactionsBy calls the XRPC method "sh.tangled.feed.listReactionsBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose reaction authorings to list.
func FeedListReactionsBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*FeedListReactionsBy_Output, error) {
	var out FeedListReactionsBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.feed.listReactionsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
