// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.countComments

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedCountCommentsNSID = "sh.tangled.feed.countComments"
)

// FeedCountComments_Output is the output of a sh.tangled.feed.countComments call.
type FeedCountComments_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// FeedCountComments calls the XRPC method "sh.tangled.feed.countComments".
//
// subject: Record AT-URI the comments attach to.
func FeedCountComments(ctx context.Context, c util.LexClient, subject string) (*FeedCountComments_Output, error) {
	var out FeedCountComments_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.feed.countComments", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
