// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.countStars

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedCountStarsNSID = "sh.tangled.feed.countStars"
)

// FeedCountStars_Output is the output of a sh.tangled.feed.countStars call.
type FeedCountStars_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// FeedCountStars calls the XRPC method "sh.tangled.feed.countStars".
//
// subject: Repo DID to list star edges for.
func FeedCountStars(ctx context.Context, c util.LexClient, subject string) (*FeedCountStars_Output, error) {
	var out FeedCountStars_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.feed.countStars", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
