// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.listStars

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedListStarsNSID = "sh.tangled.feed.listStars"
)

// FeedListStars_ListItem is a "listItem" in the sh.tangled.feed.listStars schema.
type FeedListStars_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.feed.star record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// FeedListStars_Output is the output of a sh.tangled.feed.listStars call.
type FeedListStars_Output struct {
	Cursor *string                   `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*FeedListStars_ListItem `json:"items" cborgen:"items"`
}

// FeedListStars calls the XRPC method "sh.tangled.feed.listStars".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Repo DID to list star edges for.
func FeedListStars(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*FeedListStars_Output, error) {
	var out FeedListStars_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.feed.listStars", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
