// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.listReactions

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedListReactionsNSID = "sh.tangled.feed.listReactions"
)

// FeedListReactions_ListItem is a "listItem" in the sh.tangled.feed.listReactions schema.
type FeedListReactions_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.feed.reaction record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// FeedListReactions_Output is the output of a sh.tangled.feed.listReactions call.
type FeedListReactions_Output struct {
	Cursor *string                       `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*FeedListReactions_ListItem `json:"items" cborgen:"items"`
}

// FeedListReactions calls the XRPC method "sh.tangled.feed.listReactions".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Record AT-URI the reactions target.
func FeedListReactions(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*FeedListReactions_Output, error) {
	var out FeedListReactions_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.feed.listReactions", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
