// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.countReactionsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedCountReactionsByNSID = "sh.tangled.feed.countReactionsBy"
)

// FeedCountReactionsBy_Output is the output of a sh.tangled.feed.countReactionsBy call.
type FeedCountReactionsBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// FeedCountReactionsBy calls the XRPC method "sh.tangled.feed.countReactionsBy".
//
// subject: Actor DID whose reaction authorings to list.
func FeedCountReactionsBy(ctx context.Context, c util.LexClient, subject string) (*FeedCountReactionsBy_Output, error) {
	var out FeedCountReactionsBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.feed.countReactionsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
