// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.countCommentsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedCountCommentsByNSID = "sh.tangled.feed.countCommentsBy"
)

// FeedCountCommentsBy_Output is the output of a sh.tangled.feed.countCommentsBy call.
type FeedCountCommentsBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// FeedCountCommentsBy calls the XRPC method "sh.tangled.feed.countCommentsBy".
//
// subject: Actor DID whose comment authorings to list.
func FeedCountCommentsBy(ctx context.Context, c util.LexClient, subject string) (*FeedCountCommentsBy_Output, error) {
	var out FeedCountCommentsBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.feed.countCommentsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
