// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.listCommentsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedListCommentsByNSID = "sh.tangled.feed.listCommentsBy"
)

// FeedListCommentsBy_Output is the output of a sh.tangled.feed.listCommentsBy call.
type FeedListCommentsBy_Output struct {
	Cursor *string                      `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*FeedListComments_ListItem `json:"items" cborgen:"items"`
}

// FeedListCommentsBy calls the XRPC method "sh.tangled.feed.listCommentsBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose comment authorings to list.
func FeedListCommentsBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*FeedListCommentsBy_Output, error) {
	var out FeedListCommentsBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.feed.listCommentsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
