// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.feed.listStarsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	FeedListStarsByNSID = "sh.tangled.feed.listStarsBy"
)

// FeedListStarsBy_Output is the output of a sh.tangled.feed.listStarsBy call.
type FeedListStarsBy_Output struct {
	Cursor *string                   `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*FeedListStars_ListItem `json:"items" cborgen:"items"`
}

// FeedListStarsBy calls the XRPC method "sh.tangled.feed.listStarsBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose star authorings to list.
func FeedListStarsBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*FeedListStarsBy_Output, error) {
	var out FeedListStarsBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.feed.listStarsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
