// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.focus.endSession

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempFocusEndSessionNSID = "org.tangled.temp.focus.endSession"
)

// TempFocusEndSession calls the XRPC method "org.tangled.temp.focus.endSession".
func TempFocusEndSession(ctx context.Context, c util.LexClient) error {
	if err := c.LexDo(ctx, util.Procedure, "", "org.tangled.temp.focus.endSession", nil, nil, nil); err != nil {
		return err
	}

	return nil
}
