// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.git.countRefUpdates

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GitCountRefUpdatesNSID = "sh.tangled.git.countRefUpdates"
)

// GitCountRefUpdates_Output is the output of a sh.tangled.git.countRefUpdates call.
type GitCountRefUpdates_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// GitCountRefUpdates calls the XRPC method "sh.tangled.git.countRefUpdates".
//
// subject: Repo DID whose ref-update records to list.
func GitCountRefUpdates(ctx context.Context, c util.LexClient, subject string) (*GitCountRefUpdates_Output, error) {
	var out GitCountRefUpdates_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.git.countRefUpdates", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
