// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.git.countRefUpdatesBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GitCountRefUpdatesByNSID = "sh.tangled.git.countRefUpdatesBy"
)

// GitCountRefUpdatesBy_Output is the output of a sh.tangled.git.countRefUpdatesBy call.
type GitCountRefUpdatesBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// GitCountRefUpdatesBy calls the XRPC method "sh.tangled.git.countRefUpdatesBy".
//
// subject: Actor DID whose ref-update authorings to list.
func GitCountRefUpdatesBy(ctx context.Context, c util.LexClient, subject string) (*GitCountRefUpdatesBy_Output, error) {
	var out GitCountRefUpdatesBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.git.countRefUpdatesBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
