// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.git.listRefUpdatesBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GitListRefUpdatesByNSID = "sh.tangled.git.listRefUpdatesBy"
)

// GitListRefUpdatesBy_Output is the output of a sh.tangled.git.listRefUpdatesBy call.
type GitListRefUpdatesBy_Output struct {
	Cursor *string                       `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*GitListRefUpdates_ListItem `json:"items" cborgen:"items"`
}

// GitListRefUpdatesBy calls the XRPC method "sh.tangled.git.listRefUpdatesBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose ref-update authorings to list.
func GitListRefUpdatesBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*GitListRefUpdatesBy_Output, error) {
	var out GitListRefUpdatesBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.git.listRefUpdatesBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
