// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.git.listRefUpdates

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GitListRefUpdatesNSID = "sh.tangled.git.listRefUpdates"
)

// GitListRefUpdates_ListItem is a "listItem" in the sh.tangled.git.listRefUpdates schema.
type GitListRefUpdates_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.git.refUpdate record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// GitListRefUpdates_Output is the output of a sh.tangled.git.listRefUpdates call.
type GitListRefUpdates_Output struct {
	Cursor *string                       `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*GitListRefUpdates_ListItem `json:"items" cborgen:"items"`
}

// GitListRefUpdates calls the XRPC method "sh.tangled.git.listRefUpdates".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Repo DID whose ref-update records to list.
func GitListRefUpdates(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*GitListRefUpdates_Output, error) {
	var out GitListRefUpdates_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.git.listRefUpdates", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
