// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.graph.countVouchesBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GraphCountVouchesByNSID = "sh.tangled.graph.countVouchesBy"
)

// GraphCountVouchesBy_Output is the output of a sh.tangled.graph.countVouchesBy call.
type GraphCountVouchesBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// GraphCountVouchesBy calls the XRPC method "sh.tangled.graph.countVouchesBy".
//
// subject: Actor DID whose vouch authorings to list.
func GraphCountVouchesBy(ctx context.Context, c util.LexClient, subject string) (*GraphCountVouchesBy_Output, error) {
	var out GraphCountVouchesBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.graph.countVouchesBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
