// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.graph.countFollows

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GraphCountFollowsNSID = "sh.tangled.graph.countFollows"
)

// GraphCountFollows_Output is the output of a sh.tangled.graph.countFollows call.
type GraphCountFollows_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// GraphCountFollows calls the XRPC method "sh.tangled.graph.countFollows".
//
// subject: Followee DID whose inbound follows to list.
func GraphCountFollows(ctx context.Context, c util.LexClient, subject string) (*GraphCountFollows_Output, error) {
	var out GraphCountFollows_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.graph.countFollows", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
