// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.graph.listFollows

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GraphListFollowsNSID = "sh.tangled.graph.listFollows"
)

// GraphListFollows_ListItem is a "listItem" in the sh.tangled.graph.listFollows schema.
type GraphListFollows_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.graph.follow record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// GraphListFollows_Output is the output of a sh.tangled.graph.listFollows call.
type GraphListFollows_Output struct {
	Cursor *string                      `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*GraphListFollows_ListItem `json:"items" cborgen:"items"`
}

// GraphListFollows calls the XRPC method "sh.tangled.graph.listFollows".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Followee DID whose inbound follows to list.
func GraphListFollows(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*GraphListFollows_Output, error) {
	var out GraphListFollows_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.graph.listFollows", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
