// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.graph.countFollowsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GraphCountFollowsByNSID = "sh.tangled.graph.countFollowsBy"
)

// GraphCountFollowsBy_Output is the output of a sh.tangled.graph.countFollowsBy call.
type GraphCountFollowsBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// GraphCountFollowsBy calls the XRPC method "sh.tangled.graph.countFollowsBy".
//
// subject: Actor DID whose follow authorings to list.
func GraphCountFollowsBy(ctx context.Context, c util.LexClient, subject string) (*GraphCountFollowsBy_Output, error) {
	var out GraphCountFollowsBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.graph.countFollowsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
