// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.graph.vouch

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GraphVouchNSID = "sh.tangled.graph.vouch"
)

func init() {
	util.RegisterType("sh.tangled.graph.vouch", &GraphVouch{})
} //
// RECORDTYPE: GraphVouch
type GraphVouch struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.graph.vouch" cborgen:"$type,const=sh.tangled.graph.vouch"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	// kind: Whether this user is being vouched for or denounced
	Kind string `json:"kind" cborgen:"kind"`
	// reason: The reason for this vouch/denouncement
	Reason *string `json:"reason,omitempty" cborgen:"reason,omitempty"`
}
