// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.graph.listVouchesBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GraphListVouchesByNSID = "sh.tangled.graph.listVouchesBy"
)

// GraphListVouchesBy_Output is the output of a sh.tangled.graph.listVouchesBy call.
type GraphListVouchesBy_Output struct {
	Cursor *string                      `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*GraphListVouches_ListItem `json:"items" cborgen:"items"`
}

// GraphListVouchesBy calls the XRPC method "sh.tangled.graph.listVouchesBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose vouch authorings to list.
func GraphListVouchesBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*GraphListVouchesBy_Output, error) {
	var out GraphListVouchesBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.graph.listVouchesBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
