// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.graph.listFollowsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GraphListFollowsByNSID = "sh.tangled.graph.listFollowsBy"
)

// GraphListFollowsBy_Output is the output of a sh.tangled.graph.listFollowsBy call.
type GraphListFollowsBy_Output struct {
	Cursor *string                      `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*GraphListFollows_ListItem `json:"items" cborgen:"items"`
}

// GraphListFollowsBy calls the XRPC method "sh.tangled.graph.listFollowsBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose follow authorings to list.
func GraphListFollowsBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*GraphListFollowsBy_Output, error) {
	var out GraphListFollowsBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.graph.listFollowsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
