// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.graph.listVouches

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GraphListVouchesNSID = "sh.tangled.graph.listVouches"
)

// GraphListVouches_ListItem is a "listItem" in the sh.tangled.graph.listVouches schema.
type GraphListVouches_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.graph.vouch record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// GraphListVouches_Output is the output of a sh.tangled.graph.listVouches call.
type GraphListVouches_Output struct {
	Cursor *string                      `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*GraphListVouches_ListItem `json:"items" cborgen:"items"`
}

// GraphListVouches calls the XRPC method "sh.tangled.graph.listVouches".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Vouchee DID whose inbound vouches to list.
func GraphListVouches(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*GraphListVouches_Output, error) {
	var out GraphListVouches_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.graph.listVouches", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
