// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.graph.countVouches

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GraphCountVouchesNSID = "sh.tangled.graph.countVouches"
)

// GraphCountVouches_Output is the output of a sh.tangled.graph.countVouches call.
type GraphCountVouches_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// GraphCountVouches calls the XRPC method "sh.tangled.graph.countVouches".
//
// subject: Vouchee DID whose inbound vouches to list.
func GraphCountVouches(ctx context.Context, c util.LexClient, subject string) (*GraphCountVouches_Output, error) {
	var out GraphCountVouches_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.graph.countVouches", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
