// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.issue.listStatesBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoIssueListStatesByNSID = "sh.tangled.repo.issue.listStatesBy"
)

// RepoIssueListStatesBy_Output is the output of a sh.tangled.repo.issue.listStatesBy call.
type RepoIssueListStatesBy_Output struct {
	Cursor *string                         `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*RepoIssueListStates_ListItem `json:"items" cborgen:"items"`
}

// RepoIssueListStatesBy calls the XRPC method "sh.tangled.repo.issue.listStatesBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose issue-state authorings to list.
func RepoIssueListStatesBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*RepoIssueListStatesBy_Output, error) {
	var out RepoIssueListStatesBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.issue.listStatesBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
