// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.issue.state

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoIssueStateNSID = "sh.tangled.repo.issue.state"
)

func init() {
	util.RegisterType("sh.tangled.repo.issue.state", &RepoIssueState{})
} //
// RECORDTYPE: RepoIssueState
type RepoIssueState struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.repo.issue.state" cborgen:"$type,const=sh.tangled.repo.issue.state"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	Issue         string `json:"issue" cborgen:"issue"`
	// state: state of the issue
	State string `json:"state" cborgen:"state"`
}
