// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.issue.countStates

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoIssueCountStatesNSID = "sh.tangled.repo.issue.countStates"
)

// RepoIssueCountStates_Output is the output of a sh.tangled.repo.issue.countStates call.
type RepoIssueCountStates_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// RepoIssueCountStates calls the XRPC method "sh.tangled.repo.issue.countStates".
//
// subject: Issue AT-URI whose state records to list.
func RepoIssueCountStates(ctx context.Context, c util.LexClient, subject string) (*RepoIssueCountStates_Output, error) {
	var out RepoIssueCountStates_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.issue.countStates", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
