// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.issue.countStatesBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoIssueCountStatesByNSID = "sh.tangled.repo.issue.countStatesBy"
)

// RepoIssueCountStatesBy_Output is the output of a sh.tangled.repo.issue.countStatesBy call.
type RepoIssueCountStatesBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// RepoIssueCountStatesBy calls the XRPC method "sh.tangled.repo.issue.countStatesBy".
//
// subject: Actor DID whose issue-state authorings to list.
func RepoIssueCountStatesBy(ctx context.Context, c util.LexClient, subject string) (*RepoIssueCountStatesBy_Output, error) {
	var out RepoIssueCountStatesBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.issue.countStatesBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
