// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.issue.listStates

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoIssueListStatesNSID = "sh.tangled.repo.issue.listStates"
)

// RepoIssueListStates_ListItem is a "listItem" in the sh.tangled.repo.issue.listStates schema.
type RepoIssueListStates_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.repo.issue.state record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// RepoIssueListStates_Output is the output of a sh.tangled.repo.issue.listStates call.
type RepoIssueListStates_Output struct {
	Cursor *string                         `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*RepoIssueListStates_ListItem `json:"items" cborgen:"items"`
}

// RepoIssueListStates calls the XRPC method "sh.tangled.repo.issue.listStates".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Issue AT-URI whose state records to list.
func RepoIssueListStates(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*RepoIssueListStates_Output, error) {
	var out RepoIssueListStates_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.issue.listStates", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
