// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot.countMembers

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	KnotCountMembersNSID = "sh.tangled.knot.countMembers"
)

// KnotCountMembers_Output is the output of a sh.tangled.knot.countMembers call.
type KnotCountMembers_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// KnotCountMembers calls the XRPC method "sh.tangled.knot.countMembers".
//
// subject: Knot identifier whose member records to list.
func KnotCountMembers(ctx context.Context, c util.LexClient, subject string) (*KnotCountMembers_Output, error) {
	var out KnotCountMembers_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.knot.countMembers", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
