// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot.listMembersBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	KnotListMembersByNSID = "sh.tangled.knot.listMembersBy"
)

// KnotListMembersBy_Output is the output of a sh.tangled.knot.listMembersBy call.
type KnotListMembersBy_Output struct {
	Cursor *string                     `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*KnotListMembers_ListItem `json:"items" cborgen:"items"`
}

// KnotListMembersBy calls the XRPC method "sh.tangled.knot.listMembersBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose knot-member authorings to list.
func KnotListMembersBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*KnotListMembersBy_Output, error) {
	var out KnotListMembersBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.knot.listMembersBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
