// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot.countMembersBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	KnotCountMembersByNSID = "sh.tangled.knot.countMembersBy"
)

// KnotCountMembersBy_Output is the output of a sh.tangled.knot.countMembersBy call.
type KnotCountMembersBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// KnotCountMembersBy calls the XRPC method "sh.tangled.knot.countMembersBy".
//
// subject: Actor DID whose knot-member authorings to list.
func KnotCountMembersBy(ctx context.Context, c util.LexClient, subject string) (*KnotCountMembersBy_Output, error) {
	var out KnotCountMembersBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.knot.countMembersBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
