// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot.memberAcceptance

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	KnotMemberAcceptanceNSID = "sh.tangled.knot.memberAcceptance"
)

func init() {
	util.RegisterType("sh.tangled.knot.memberAcceptance", &KnotMemberAcceptance{})
} //
// RECORDTYPE: KnotMemberAcceptance
type KnotMemberAcceptance struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.knot.memberAcceptance" cborgen:"$type,const=sh.tangled.knot.memberAcceptance"`
	// createdAt: Invite acceptance timestamp
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
}
