// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot.addMember

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	KnotAddMemberNSID = "sh.tangled.knot.addMember"
)

// KnotAddMember_Input is the input argument to a sh.tangled.knot.addMember call.
type KnotAddMember_Input struct {
	// subject: DID of the member to add
	Subject string `json:"subject" cborgen:"subject"`
}

// KnotAddMember calls the XRPC method "sh.tangled.knot.addMember".
func KnotAddMember(ctx context.Context, c util.LexClient, input *KnotAddMember_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "sh.tangled.knot.addMember", nil, input, nil); err != nil {
		return err
	}

	return nil
}
