// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot.subscribeRepos

const (
	KnotSubscribeReposNSID = "sh.tangled.knot.subscribeRepos"
)

// KnotSubscribeRepos_GitSync1 is a "gitSync1" in the sh.tangled.knot.subscribeRepos schema.
type KnotSubscribeRepos_GitSync1 struct {
	// did: Repository DID identifier
	Did string `json:"did" cborgen:"did"`
	// seq: The stream sequence number of this message.
	Seq int64 `json:"seq" cborgen:"seq"`
}

// KnotSubscribeRepos_GitSync2 is a "gitSync2" in the sh.tangled.knot.subscribeRepos schema.
type KnotSubscribeRepos_GitSync2 struct {
	// did: Repository AT-URI identifier
	Did *string `json:"did,omitempty" cborgen:"did,omitempty"`
	// seq: The stream sequence number of this message.
	Seq int64 `json:"seq" cborgen:"seq"`
}

// KnotSubscribeRepos_Identity is a "identity" in the sh.tangled.knot.subscribeRepos schema.
type KnotSubscribeRepos_Identity struct {
	// did: Repository DID identifier
	Did string `json:"did" cborgen:"did"`
	// seq: The stream sequence number of this message.
	Seq  int64  `json:"seq" cborgen:"seq"`
	Time string `json:"time" cborgen:"time"`
}
