// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot.removeMember

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	KnotRemoveMemberNSID = "sh.tangled.knot.removeMember"
)

// KnotRemoveMember_Input is the input argument to a sh.tangled.knot.removeMember call.
type KnotRemoveMember_Input struct {
	// subject: DID of the member to remove
	Subject string `json:"subject" cborgen:"subject"`
}

// KnotRemoveMember calls the XRPC method "sh.tangled.knot.removeMember".
func KnotRemoveMember(ctx context.Context, c util.LexClient, input *KnotRemoveMember_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "sh.tangled.knot.removeMember", nil, input, nil); err != nil {
		return err
	}

	return nil
}
