// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot.memberInvite

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	KnotMemberInviteNSID = "sh.tangled.knot.memberInvite"
)

func init() {
	util.RegisterType("sh.tangled.knot.memberInvite", &KnotMemberInvite{})
} //
// RECORDTYPE: KnotMemberInvite
type KnotMemberInvite struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.knot.memberInvite" cborgen:"$type,const=sh.tangled.knot.memberInvite"`
	// createdAt: Invite issue timestamp
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
}
