// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot.countKnots

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	KnotCountKnotsNSID = "sh.tangled.knot.countKnots"
)

// KnotCountKnots_Output is the output of a sh.tangled.knot.countKnots call.
type KnotCountKnots_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// KnotCountKnots calls the XRPC method "sh.tangled.knot.countKnots".
//
// subject: Owner DID whose knot records to list.
func KnotCountKnots(ctx context.Context, c util.LexClient, subject string) (*KnotCountKnots_Output, error) {
	var out KnotCountKnots_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.knot.countKnots", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
