// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.knot.listKnots

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	KnotListKnotsNSID = "sh.tangled.knot.listKnots"
)

// KnotListKnots_ListItem is a "listItem" in the sh.tangled.knot.listKnots schema.
type KnotListKnots_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.knot record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// KnotListKnots_Output is the output of a sh.tangled.knot.listKnots call.
type KnotListKnots_Output struct {
	Cursor *string                   `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*KnotListKnots_ListItem `json:"items" cborgen:"items"`
}

// KnotListKnots calls the XRPC method "sh.tangled.knot.listKnots".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Owner DID whose knot records to list.
func KnotListKnots(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*KnotListKnots_Output, error) {
	var out KnotListKnots_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.knot.listKnots", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
