// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.label.listOps

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	LabelListOpsNSID = "sh.tangled.label.listOps"
)

// LabelListOps_ListItem is a "listItem" in the sh.tangled.label.listOps schema.
type LabelListOps_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.label.op record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// LabelListOps_Output is the output of a sh.tangled.label.listOps call.
type LabelListOps_Output struct {
	Cursor *string                  `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*LabelListOps_ListItem `json:"items" cborgen:"items"`
}

// LabelListOps calls the XRPC method "sh.tangled.label.listOps".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Scope identifier whose label op records to list.
func LabelListOps(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*LabelListOps_Output, error) {
	var out LabelListOps_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.label.listOps", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
