// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.label.countOpsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	LabelCountOpsByNSID = "sh.tangled.label.countOpsBy"
)

// LabelCountOpsBy_Output is the output of a sh.tangled.label.countOpsBy call.
type LabelCountOpsBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// LabelCountOpsBy calls the XRPC method "sh.tangled.label.countOpsBy".
//
// subject: Actor DID whose label-op authorings to list.
func LabelCountOpsBy(ctx context.Context, c util.LexClient, subject string) (*LabelCountOpsBy_Output, error) {
	var out LabelCountOpsBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.label.countOpsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
