// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.label.countDefinitions

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	LabelCountDefinitionsNSID = "sh.tangled.label.countDefinitions"
)

// LabelCountDefinitions_Output is the output of a sh.tangled.label.countDefinitions call.
type LabelCountDefinitions_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// LabelCountDefinitions calls the XRPC method "sh.tangled.label.countDefinitions".
//
// subject: Scope identifier whose label definitions to list.
func LabelCountDefinitions(ctx context.Context, c util.LexClient, subject string) (*LabelCountDefinitions_Output, error) {
	var out LabelCountDefinitions_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.label.countDefinitions", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
