// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.label.listDefinitions

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	LabelListDefinitionsNSID = "sh.tangled.label.listDefinitions"
)

// LabelListDefinitions_ListItem is a "listItem" in the sh.tangled.label.listDefinitions schema.
type LabelListDefinitions_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.label.definition record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// LabelListDefinitions_Output is the output of a sh.tangled.label.listDefinitions call.
type LabelListDefinitions_Output struct {
	Cursor *string                          `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*LabelListDefinitions_ListItem `json:"items" cborgen:"items"`
}

// LabelListDefinitions calls the XRPC method "sh.tangled.label.listDefinitions".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Scope identifier whose label definitions to list.
func LabelListDefinitions(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*LabelListDefinitions_Output, error) {
	var out LabelListDefinitions_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.label.listDefinitions", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
