// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.label.listOpsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	LabelListOpsByNSID = "sh.tangled.label.listOpsBy"
)

// LabelListOpsBy_Output is the output of a sh.tangled.label.listOpsBy call.
type LabelListOpsBy_Output struct {
	Cursor *string                  `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*LabelListOps_ListItem `json:"items" cborgen:"items"`
}

// LabelListOpsBy calls the XRPC method "sh.tangled.label.listOpsBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose label-op authorings to list.
func LabelListOpsBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*LabelListOpsBy_Output, error) {
	var out LabelListOpsBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.label.listOpsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
