// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.label.countOps

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	LabelCountOpsNSID = "sh.tangled.label.countOps"
)

// LabelCountOps_Output is the output of a sh.tangled.label.countOps call.
type LabelCountOps_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// LabelCountOps calls the XRPC method "sh.tangled.label.countOps".
//
// subject: Scope identifier whose label op records to list.
func LabelCountOps(ctx context.Context, c util.LexClient, subject string) (*LabelCountOps_Output, error) {
	var out LabelCountOps_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.label.countOps", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
