// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.markup.markdown

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	MarkupMarkdownNSID = "sh.tangled.markup.markdown"
)

func init() {
	util.RegisterType("sh.tangled.markup.markdown#main", &MarkupMarkdown{})
} // MarkupMarkdown is a "main" in the sh.tangled.markup.markdown schema.
// Tangled Flavored Markdown format text
//
// RECORDTYPE: MarkupMarkdown
type MarkupMarkdown struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.markup.markdown" cborgen:"$type,const=sh.tangled.markup.markdown"`
	// blobs: list of blobs referenced in markdown
	Blobs []*util.LexBlob `json:"blobs,omitempty" cborgen:"blobs,omitempty"`
	// original: Original Markdown before post-processing. Used to restore original input on edit.
	Original *string `json:"original,omitempty" cborgen:"original,omitempty"`
	// text: Final post-processed markdown content that will be rendered
	Text string `json:"text" cborgen:"text"`
}
