// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.notification.markAllRead

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempNotificationMarkAllReadNSID = "org.tangled.temp.notification.markAllRead"
)

// TempNotificationMarkAllRead calls the XRPC method "org.tangled.temp.notification.markAllRead".
func TempNotificationMarkAllRead(ctx context.Context, c util.LexClient) error {
	if err := c.LexDo(ctx, util.Procedure, "", "org.tangled.temp.notification.markAllRead", nil, nil, nil); err != nil {
		return err
	}

	return nil
}
