// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.notification.getUnreadCount

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempNotificationGetUnreadCountNSID = "org.tangled.temp.notification.getUnreadCount"
)

// TempNotificationGetUnreadCount_Output is the output of a org.tangled.temp.notification.getUnreadCount call.
type TempNotificationGetUnreadCount_Output struct {
	Count int64 `json:"count" cborgen:"count"`
}

// TempNotificationGetUnreadCount calls the XRPC method "org.tangled.temp.notification.getUnreadCount".
func TempNotificationGetUnreadCount(ctx context.Context, c util.LexClient) (*TempNotificationGetUnreadCount_Output, error) {
	var out TempNotificationGetUnreadCount_Output
	if err := c.LexDo(ctx, util.Query, "", "org.tangled.temp.notification.getUnreadCount", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
