// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.notification.updateSeen

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempNotificationUpdateSeenNSID = "org.tangled.temp.notification.updateSeen"
)

// TempNotificationUpdateSeen_Input is the input argument to a org.tangled.temp.notification.updateSeen call.
type TempNotificationUpdateSeen_Input struct {
	// id: ID of the notification to update.
	Id   int64 `json:"id" cborgen:"id"`
	Read bool  `json:"read" cborgen:"read"`
}

// TempNotificationUpdateSeen calls the XRPC method "org.tangled.temp.notification.updateSeen".
func TempNotificationUpdateSeen(ctx context.Context, c util.LexClient, input *TempNotificationUpdateSeen_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "org.tangled.temp.notification.updateSeen", nil, input, nil); err != nil {
		return err
	}

	return nil
}
