// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.notification.deleteNotification

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempNotificationDeleteNotificationNSID = "org.tangled.temp.notification.deleteNotification"
)

// TempNotificationDeleteNotification_Input is the input argument to a org.tangled.temp.notification.deleteNotification call.
type TempNotificationDeleteNotification_Input struct {
	// uri: at-uri of the notification to delete.
	Uri string `json:"uri" cborgen:"uri"`
}

// TempNotificationDeleteNotification calls the XRPC method "org.tangled.temp.notification.deleteNotification".
func TempNotificationDeleteNotification(ctx context.Context, c util.LexClient, input *TempNotificationDeleteNotification_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "org.tangled.temp.notification.deleteNotification", nil, input, nil); err != nil {
		return err
	}

	return nil
}
