// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.pipeline.status

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	PipelineStatusNSID = "sh.tangled.pipeline.status"
)

func init() {
	util.RegisterType("sh.tangled.pipeline.status", &PipelineStatus{})
} //
// DEPRECATED: use sh.tangled.ci.pipeline instead
//
// RECORDTYPE: PipelineStatus
type PipelineStatus struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.pipeline.status" cborgen:"$type,const=sh.tangled.pipeline.status"`
	// createdAt: time of creation of this status update
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// error: error message if failed
	Error *string `json:"error,omitempty" cborgen:"error,omitempty"`
	// exitCode: exit code if failed
	ExitCode *int64 `json:"exitCode,omitempty" cborgen:"exitCode,omitempty"`
	// pipeline: ATURI of the pipeline
	Pipeline string `json:"pipeline" cborgen:"pipeline"`
	// status: status of the workflow
	Status string `json:"status" cborgen:"status"`
	// workflow: name of the workflow within this pipeline
	Workflow string `json:"workflow" cborgen:"workflow"`
}
