// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.pipeline.countStatusesBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	PipelineCountStatusesByNSID = "sh.tangled.pipeline.countStatusesBy"
)

// PipelineCountStatusesBy_Output is the output of a sh.tangled.pipeline.countStatusesBy call.
type PipelineCountStatusesBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// PipelineCountStatusesBy calls the XRPC method "sh.tangled.pipeline.countStatusesBy".
//
// subject: Actor DID whose pipeline-status authorings to list.
func PipelineCountStatusesBy(ctx context.Context, c util.LexClient, subject string) (*PipelineCountStatusesBy_Output, error) {
	var out PipelineCountStatusesBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.pipeline.countStatusesBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
