// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.pipeline.listPipelinesBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	PipelineListPipelinesByNSID = "sh.tangled.pipeline.listPipelinesBy"
)

// PipelineListPipelinesBy_Output is the output of a sh.tangled.pipeline.listPipelinesBy call.
type PipelineListPipelinesBy_Output struct {
	Cursor *string                           `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*PipelineListPipelines_ListItem `json:"items" cborgen:"items"`
}

// PipelineListPipelinesBy calls the XRPC method "sh.tangled.pipeline.listPipelinesBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose pipeline authorings to list.
func PipelineListPipelinesBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*PipelineListPipelinesBy_Output, error) {
	var out PipelineListPipelinesBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.pipeline.listPipelinesBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
