// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.pipeline.listPipelines

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	PipelineListPipelinesNSID = "sh.tangled.pipeline.listPipelines"
)

// PipelineListPipelines_ListItem is a "listItem" in the sh.tangled.pipeline.listPipelines schema.
type PipelineListPipelines_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.pipeline record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// PipelineListPipelines_Output is the output of a sh.tangled.pipeline.listPipelines call.
type PipelineListPipelines_Output struct {
	Cursor *string                           `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*PipelineListPipelines_ListItem `json:"items" cborgen:"items"`
}

// PipelineListPipelines calls the XRPC method "sh.tangled.pipeline.listPipelines".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Repo or spindle identifier whose pipeline records to list.
func PipelineListPipelines(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*PipelineListPipelines_Output, error) {
	var out PipelineListPipelines_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.pipeline.listPipelines", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
