// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.pipeline.listStatuses

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	PipelineListStatusesNSID = "sh.tangled.pipeline.listStatuses"
)

// PipelineListStatuses_ListItem is a "listItem" in the sh.tangled.pipeline.listStatuses schema.
type PipelineListStatuses_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.pipeline.status record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// PipelineListStatuses_Output is the output of a sh.tangled.pipeline.listStatuses call.
type PipelineListStatuses_Output struct {
	Cursor *string                          `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*PipelineListStatuses_ListItem `json:"items" cborgen:"items"`
}

// PipelineListStatuses calls the XRPC method "sh.tangled.pipeline.listStatuses".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Pipeline AT-URI whose status records to list.
func PipelineListStatuses(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*PipelineListStatuses_Output, error) {
	var out PipelineListStatuses_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.pipeline.listStatuses", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
