// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.pipeline.countStatuses

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	PipelineCountStatusesNSID = "sh.tangled.pipeline.countStatuses"
)

// PipelineCountStatuses_Output is the output of a sh.tangled.pipeline.countStatuses call.
type PipelineCountStatuses_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// PipelineCountStatuses calls the XRPC method "sh.tangled.pipeline.countStatuses".
//
// subject: Pipeline AT-URI whose status records to list.
func PipelineCountStatuses(ctx context.Context, c util.LexClient, subject string) (*PipelineCountStatuses_Output, error) {
	var out PipelineCountStatuses_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.pipeline.countStatuses", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
