// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.pipeline.listStatusesBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	PipelineListStatusesByNSID = "sh.tangled.pipeline.listStatusesBy"
)

// PipelineListStatusesBy_Output is the output of a sh.tangled.pipeline.listStatusesBy call.
type PipelineListStatusesBy_Output struct {
	Cursor *string                          `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*PipelineListStatuses_ListItem `json:"items" cborgen:"items"`
}

// PipelineListStatusesBy calls the XRPC method "sh.tangled.pipeline.listStatusesBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose pipeline-status authorings to list.
func PipelineListStatusesBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*PipelineListStatusesBy_Output, error) {
	var out PipelineListStatusesBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.pipeline.listStatusesBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
