// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.pipeline.countPipelinesBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	PipelineCountPipelinesByNSID = "sh.tangled.pipeline.countPipelinesBy"
)

// PipelineCountPipelinesBy_Output is the output of a sh.tangled.pipeline.countPipelinesBy call.
type PipelineCountPipelinesBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// PipelineCountPipelinesBy calls the XRPC method "sh.tangled.pipeline.countPipelinesBy".
//
// subject: Actor DID whose pipeline authorings to list.
func PipelineCountPipelinesBy(ctx context.Context, c util.LexClient, subject string) (*PipelineCountPipelinesBy_Output, error) {
	var out PipelineCountPipelinesBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.pipeline.countPipelinesBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
