// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.publicKey.listKeys

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	PublicKeyListKeysNSID = "sh.tangled.publicKey.listKeys"
)

// PublicKeyListKeys_ListItem is a "listItem" in the sh.tangled.publicKey.listKeys schema.
type PublicKeyListKeys_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.publicKey record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// PublicKeyListKeys_Output is the output of a sh.tangled.publicKey.listKeys call.
type PublicKeyListKeys_Output struct {
	Cursor *string                       `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*PublicKeyListKeys_ListItem `json:"items" cborgen:"items"`
}

// PublicKeyListKeys calls the XRPC method "sh.tangled.publicKey.listKeys".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Owner DID whose public-key records to list.
func PublicKeyListKeys(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*PublicKeyListKeys_Output, error) {
	var out PublicKeyListKeys_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.publicKey.listKeys", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
