// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.publicKey.countKeys

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	PublicKeyCountKeysNSID = "sh.tangled.publicKey.countKeys"
)

// PublicKeyCountKeys_Output is the output of a sh.tangled.publicKey.countKeys call.
type PublicKeyCountKeys_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// PublicKeyCountKeys calls the XRPC method "sh.tangled.publicKey.countKeys".
//
// subject: Owner DID whose public-key records to list.
func PublicKeyCountKeys(ctx context.Context, c util.LexClient, subject string) (*PublicKeyCountKeys_Output, error) {
	var out PublicKeyCountKeys_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.publicKey.countKeys", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
