// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull.countStatuses

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoPullCountStatusesNSID = "sh.tangled.repo.pull.countStatuses"
)

// RepoPullCountStatuses_Output is the output of a sh.tangled.repo.pull.countStatuses call.
type RepoPullCountStatuses_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// RepoPullCountStatuses calls the XRPC method "sh.tangled.repo.pull.countStatuses".
//
// subject: Pull AT-URI whose status records to list.
func RepoPullCountStatuses(ctx context.Context, c util.LexClient, subject string) (*RepoPullCountStatuses_Output, error) {
	var out RepoPullCountStatuses_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.pull.countStatuses", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
