// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull.listStatuses

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoPullListStatusesNSID = "sh.tangled.repo.pull.listStatuses"
)

// RepoPullListStatuses_ListItem is a "listItem" in the sh.tangled.repo.pull.listStatuses schema.
type RepoPullListStatuses_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.repo.pull.status record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// RepoPullListStatuses_Output is the output of a sh.tangled.repo.pull.listStatuses call.
type RepoPullListStatuses_Output struct {
	Cursor *string                          `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*RepoPullListStatuses_ListItem `json:"items" cborgen:"items"`
}

// RepoPullListStatuses calls the XRPC method "sh.tangled.repo.pull.listStatuses".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Pull AT-URI whose status records to list.
func RepoPullListStatuses(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*RepoPullListStatuses_Output, error) {
	var out RepoPullListStatuses_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.pull.listStatuses", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
