// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull.status

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoPullStatusNSID = "sh.tangled.repo.pull.status"
)

func init() {
	util.RegisterType("sh.tangled.repo.pull.status", &RepoPullStatus{})
} //
// RECORDTYPE: RepoPullStatus
type RepoPullStatus struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.repo.pull.status" cborgen:"$type,const=sh.tangled.repo.pull.status"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	Pull          string `json:"pull" cborgen:"pull"`
	// status: status of the pull request
	Status string `json:"status" cborgen:"status"`
}
