// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.pull.countStatusesBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoPullCountStatusesByNSID = "sh.tangled.repo.pull.countStatusesBy"
)

// RepoPullCountStatusesBy_Output is the output of a sh.tangled.repo.pull.countStatusesBy call.
type RepoPullCountStatusesBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// RepoPullCountStatusesBy calls the XRPC method "sh.tangled.repo.pull.countStatusesBy".
//
// subject: Actor DID whose pull-status authorings to list.
func RepoPullCountStatusesBy(ctx context.Context, c util.LexClient, subject string) (*RepoPullCountStatusesBy_Output, error) {
	var out RepoPullCountStatusesBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.pull.countStatusesBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
