// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.listArtifactsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoListArtifactsByNSID = "sh.tangled.repo.listArtifactsBy"
)

// RepoListArtifactsBy_Output is the output of a sh.tangled.repo.listArtifactsBy call.
type RepoListArtifactsBy_Output struct {
	Cursor *string                       `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*RepoListArtifacts_ListItem `json:"items" cborgen:"items"`
}

// RepoListArtifactsBy calls the XRPC method "sh.tangled.repo.listArtifactsBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose artifact authorings to list.
func RepoListArtifactsBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*RepoListArtifactsBy_Output, error) {
	var out RepoListArtifactsBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.listArtifactsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
