// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.repo.deleteWebhook

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempRepoDeleteWebhookNSID = "org.tangled.temp.repo.deleteWebhook"
)

// TempRepoDeleteWebhook_Input is the input argument to a org.tangled.temp.repo.deleteWebhook call.
type TempRepoDeleteWebhook_Input struct {
	// id: Webhook ID to delete.
	Id int64 `json:"id" cborgen:"id"`
	// repoDid: DID of the repository as minted by the knot.
	RepoDid string `json:"repoDid" cborgen:"repoDid"`
}

// TempRepoDeleteWebhook calls the XRPC method "org.tangled.temp.repo.deleteWebhook".
func TempRepoDeleteWebhook(ctx context.Context, c util.LexClient, input *TempRepoDeleteWebhook_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "org.tangled.temp.repo.deleteWebhook", nil, input, nil); err != nil {
		return err
	}

	return nil
}
