// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.forkSync

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoForkSyncNSID = "sh.tangled.repo.forkSync"
)

// RepoForkSync_Input is the input argument to a sh.tangled.repo.forkSync call.
type RepoForkSync_Input struct {
	// branch: Branch to sync
	Branch string `json:"branch" cborgen:"branch"`
	// did: DID of the fork owner. A knot without the repo-did-input capability reads this and name in place of repo.
	Did *string `json:"did,omitempty" cborgen:"did,omitempty"`
	// name: Name of the forked repository. A knot without the repo-did-input capability reads this and DID in place of repo.
	Name *string `json:"name,omitempty" cborgen:"name,omitempty"`
	// repo: DID of the fork to sync
	Repo string `json:"repo" cborgen:"repo"`
	// source: AT-URI of the source repository. A knot without the repo-did-input capability requires this field without reading it.
	Source *string `json:"source,omitempty" cborgen:"source,omitempty"`
}

// RepoForkSync calls the XRPC method "sh.tangled.repo.forkSync".
func RepoForkSync(ctx context.Context, c util.LexClient, input *RepoForkSync_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "sh.tangled.repo.forkSync", nil, input, nil); err != nil {
		return err
	}

	return nil
}
