// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.addCollaborator

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoAddCollaboratorNSID = "sh.tangled.repo.addCollaborator"
)

// RepoAddCollaborator_Input is the input argument to a sh.tangled.repo.addCollaborator call.
type RepoAddCollaborator_Input struct {
	// repo: DID of the repository to add the collaborator to
	Repo string `json:"repo" cborgen:"repo"`
	// subject: DID of the collaborator to add
	Subject string `json:"subject" cborgen:"subject"`
}

// RepoAddCollaborator calls the XRPC method "sh.tangled.repo.addCollaborator".
func RepoAddCollaborator(ctx context.Context, c util.LexClient, input *RepoAddCollaborator_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "sh.tangled.repo.addCollaborator", nil, input, nil); err != nil {
		return err
	}

	return nil
}
