// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.artifact

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoArtifactNSID = "sh.tangled.repo.artifact"
)

func init() {
	util.RegisterType("sh.tangled.repo.artifact", &RepoArtifact{})
} //
// RECORDTYPE: RepoArtifact
type RepoArtifact struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.repo.artifact" cborgen:"$type,const=sh.tangled.repo.artifact"`
	// artifact: the artifact
	Artifact *util.LexBlob `json:"artifact" cborgen:"artifact"`
	// createdAt: time of creation of this artifact
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// name: name of the artifact
	Name string `json:"name" cborgen:"name"`
	// repo: repo that this artifact is being uploaded to
	Repo    *string `json:"repo,omitempty" cborgen:"repo,omitempty"`
	RepoDid *string `json:"repoDid,omitempty" cborgen:"repoDid,omitempty"`
	// tag: hash of the tag object that this artifact is attached to (only annotated tags are supported)
	Tag util.LexBytes `json:"tag,omitempty" cborgen:"tag,omitempty"`
}
