// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.issue

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoIssueNSID = "sh.tangled.repo.issue"
)

func init() {
	util.RegisterType("sh.tangled.repo.issue", &RepoIssue{})
} //
// RECORDTYPE: RepoIssue
type RepoIssue struct {
	LexiconTypeID string   `json:"$type,const=sh.tangled.repo.issue" cborgen:"$type,const=sh.tangled.repo.issue"`
	Body          *string  `json:"body,omitempty" cborgen:"body,omitempty"`
	CreatedAt     string   `json:"createdAt" cborgen:"createdAt"`
	Mentions      []string `json:"mentions,omitempty" cborgen:"mentions,omitempty"`
	References    []string `json:"references,omitempty" cborgen:"references,omitempty"`
	Repo          string   `json:"repo" cborgen:"repo"`
	Title         string   `json:"title" cborgen:"title"`
}
