// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.getRepos

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoGetReposNSID = "sh.tangled.repo.getRepos"
)

// RepoGetRepos_Output is the output of a sh.tangled.repo.getRepos call.
type RepoGetRepos_Output struct {
	Items []*RepoGetRepos_RecordView `json:"items" cborgen:"items"`
}

// RepoGetRepos_RecordView is a "recordView" in the sh.tangled.repo.getRepos schema.
type RepoGetRepos_RecordView struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.repo record.
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// RepoGetRepos calls the XRPC method "sh.tangled.repo.getRepos".
//
// repos: AT-URIs of the sh.tangled.repo records to fetch. At most 50 per request.
func RepoGetRepos(ctx context.Context, c util.LexClient, repos []string) (*RepoGetRepos_Output, error) {
	var out RepoGetRepos_Output

	params := map[string]interface{}{}
	params["repos"] = repos
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.getRepos", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
