// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.countCollaborators

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoCountCollaboratorsNSID = "sh.tangled.repo.countCollaborators"
)

// RepoCountCollaborators_Output is the output of a sh.tangled.repo.countCollaborators call.
type RepoCountCollaborators_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// RepoCountCollaborators calls the XRPC method "sh.tangled.repo.countCollaborators".
//
// subject: Repo DID whose collaborator records to list.
func RepoCountCollaborators(ctx context.Context, c util.LexClient, subject string) (*RepoCountCollaborators_Output, error) {
	var out RepoCountCollaborators_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.countCollaborators", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
