// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.countIssues

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoCountIssuesNSID = "sh.tangled.repo.countIssues"
)

// RepoCountIssues_Output is the output of a sh.tangled.repo.countIssues call.
type RepoCountIssues_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// RepoCountIssues calls the XRPC method "sh.tangled.repo.countIssues".
//
// subject: Repo DID to list issues for
func RepoCountIssues(ctx context.Context, c util.LexClient, subject string) (*RepoCountIssues_Output, error) {
	var out RepoCountIssues_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.countIssues", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
