// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.listCollaboratorsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoListCollaboratorsByNSID = "sh.tangled.repo.listCollaboratorsBy"
)

// RepoListCollaboratorsBy_Output is the output of a sh.tangled.repo.listCollaboratorsBy call.
type RepoListCollaboratorsBy_Output struct {
	Cursor *string                           `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*RepoListCollaborators_ListItem `json:"items" cborgen:"items"`
}

// RepoListCollaboratorsBy calls the XRPC method "sh.tangled.repo.listCollaboratorsBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose collaborator authorings to list.
func RepoListCollaboratorsBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*RepoListCollaboratorsBy_Output, error) {
	var out RepoListCollaboratorsBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.listCollaboratorsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
