// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.deleteBranch

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoDeleteBranchNSID = "sh.tangled.repo.deleteBranch"
)

// RepoDeleteBranch_Input is the input argument to a sh.tangled.repo.deleteBranch call.
type RepoDeleteBranch_Input struct {
	Branch string `json:"branch" cborgen:"branch"`
	// repo: DID of the repository
	Repo string `json:"repo" cborgen:"repo"`
}

// RepoDeleteBranch calls the XRPC method "sh.tangled.repo.deleteBranch".
func RepoDeleteBranch(ctx context.Context, c util.LexClient, input *RepoDeleteBranch_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "sh.tangled.repo.deleteBranch", nil, input, nil); err != nil {
		return err
	}

	return nil
}
