// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.setDefaultBranch

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoSetDefaultBranchNSID = "sh.tangled.repo.setDefaultBranch"
)

// RepoSetDefaultBranch_Input is the input argument to a sh.tangled.repo.setDefaultBranch call.
type RepoSetDefaultBranch_Input struct {
	DefaultBranch string `json:"defaultBranch" cborgen:"defaultBranch"`
	// repo: DID of the repository
	Repo string `json:"repo" cborgen:"repo"`
}

// RepoSetDefaultBranch calls the XRPC method "sh.tangled.repo.setDefaultBranch".
func RepoSetDefaultBranch(ctx context.Context, c util.LexClient, input *RepoSetDefaultBranch_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "sh.tangled.repo.setDefaultBranch", nil, input, nil); err != nil {
		return err
	}

	return nil
}
