// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.listIssuesBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoListIssuesByNSID = "sh.tangled.repo.listIssuesBy"
)

// RepoListIssuesBy_Output is the output of a sh.tangled.repo.listIssuesBy call.
type RepoListIssuesBy_Output struct {
	Cursor *string                         `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*RepoListIssues_IssueListItem `json:"items" cborgen:"items"`
}

// RepoListIssuesBy calls the XRPC method "sh.tangled.repo.listIssuesBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// state: Restrict to issues whose latest derived state matches.
// subject: Actor DID whose issue authorings to list
func RepoListIssuesBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, state string, subject string) (*RepoListIssuesBy_Output, error) {
	var out RepoListIssuesBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	if state != "" {
		params["state"] = state
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.listIssuesBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
