// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.describeRepo

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoDescribeRepoNSID = "sh.tangled.repo.describeRepo"
)

// RepoDescribeRepo_Output is the output of a sh.tangled.repo.describeRepo call.
type RepoDescribeRepo_Output struct {
	// ownerDid: DID of the current owner according to the knot.
	OwnerDid string `json:"ownerDid" cborgen:"ownerDid"`
	RepoDid  string `json:"repoDid" cborgen:"repoDid"`
	// rkey: Current rkey of the sh.tangled.repo record tracked by this knot
	Rkey string `json:"rkey" cborgen:"rkey"`
}

// RepoDescribeRepo calls the XRPC method "sh.tangled.repo.describeRepo".
//
// repoDid: DID of the git repo as minted by the knot
func RepoDescribeRepo(ctx context.Context, c util.LexClient, repoDid string) (*RepoDescribeRepo_Output, error) {
	var out RepoDescribeRepo_Output

	params := map[string]interface{}{}
	params["repoDid"] = repoDid
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.describeRepo", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
