// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.removeCollaborator

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoRemoveCollaboratorNSID = "sh.tangled.repo.removeCollaborator"
)

// RepoRemoveCollaborator_Input is the input argument to a sh.tangled.repo.removeCollaborator call.
type RepoRemoveCollaborator_Input struct {
	// repo: DID of the repository to remove the collaborator from
	Repo string `json:"repo" cborgen:"repo"`
	// subject: DID of the collaborator to remove
	Subject string `json:"subject" cborgen:"subject"`
}

// RepoRemoveCollaborator calls the XRPC method "sh.tangled.repo.removeCollaborator".
func RepoRemoveCollaborator(ctx context.Context, c util.LexClient, input *RepoRemoveCollaborator_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "sh.tangled.repo.removeCollaborator", nil, input, nil); err != nil {
		return err
	}

	return nil
}
