// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.getPull

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoGetPullNSID = "sh.tangled.repo.getPull"
)

// RepoGetPull_Output is the output of a sh.tangled.repo.getPull call.
type RepoGetPull_Output struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.repo.pull record.
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// RepoGetPull calls the XRPC method "sh.tangled.repo.getPull".
//
// pull: AT-URI of the sh.tangled.repo.pull record to fetch.
func RepoGetPull(ctx context.Context, c util.LexClient, pull string) (*RepoGetPull_Output, error) {
	var out RepoGetPull_Output

	params := map[string]interface{}{}
	params["pull"] = pull
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.getPull", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
