// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.countArtifactsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoCountArtifactsByNSID = "sh.tangled.repo.countArtifactsBy"
)

// RepoCountArtifactsBy_Output is the output of a sh.tangled.repo.countArtifactsBy call.
type RepoCountArtifactsBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// RepoCountArtifactsBy calls the XRPC method "sh.tangled.repo.countArtifactsBy".
//
// subject: Actor DID whose artifact authorings to list.
func RepoCountArtifactsBy(ctx context.Context, c util.LexClient, subject string) (*RepoCountArtifactsBy_Output, error) {
	var out RepoCountArtifactsBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.countArtifactsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
