// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.collaboratorInvite

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoCollaboratorInviteNSID = "sh.tangled.repo.collaboratorInvite"
)

func init() {
	util.RegisterType("sh.tangled.repo.collaboratorInvite", &RepoCollaboratorInvite{})
} //
// RECORDTYPE: RepoCollaboratorInvite
type RepoCollaboratorInvite struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.repo.collaboratorInvite" cborgen:"$type,const=sh.tangled.repo.collaboratorInvite"`
	// createdAt: Invite issue timestamp
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
}
