// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.repo.updateSiteConfig

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempRepoUpdateSiteConfigNSID = "org.tangled.temp.repo.updateSiteConfig"
)

// TempRepoUpdateSiteConfig_Input is the input argument to a org.tangled.temp.repo.updateSiteConfig call.
type TempRepoUpdateSiteConfig_Input struct {
	// branch: Branch to deploy from.
	Branch string `json:"branch" cborgen:"branch"`
	// dir: Directory within the repository to deploy (e.g. '/' or '/docs').
	Dir string `json:"dir" cborgen:"dir"`
	// isIndex: Whether this repo should serve as the index (root) for the claimed domain.
	IsIndex *bool `json:"isIndex,omitempty" cborgen:"isIndex,omitempty"`
	// repoDid: DID of the repository as minted by the knot.
	RepoDid string `json:"repoDid" cborgen:"repoDid"`
}

// TempRepoUpdateSiteConfig calls the XRPC method "org.tangled.temp.repo.updateSiteConfig".
func TempRepoUpdateSiteConfig(ctx context.Context, c util.LexClient, input *TempRepoUpdateSiteConfig_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "org.tangled.temp.repo.updateSiteConfig", nil, input, nil); err != nil {
		return err
	}

	return nil
}
