// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.repo.disableSite

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempRepoDisableSiteNSID = "org.tangled.temp.repo.disableSite"
)

// TempRepoDisableSite_Input is the input argument to a org.tangled.temp.repo.disableSite call.
type TempRepoDisableSite_Input struct {
	// repoDid: DID of the repository as minted by the knot.
	RepoDid string `json:"repoDid" cborgen:"repoDid"`
}

// TempRepoDisableSite calls the XRPC method "org.tangled.temp.repo.disableSite".
func TempRepoDisableSite(ctx context.Context, c util.LexClient, input *TempRepoDisableSite_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "org.tangled.temp.repo.disableSite", nil, input, nil); err != nil {
		return err
	}

	return nil
}
