// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.collaboratorAcceptance

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoCollaboratorAcceptanceNSID = "sh.tangled.repo.collaboratorAcceptance"
)

func init() {
	util.RegisterType("sh.tangled.repo.collaboratorAcceptance", &RepoCollaboratorAcceptance{})
} //
// RECORDTYPE: RepoCollaboratorAcceptance
type RepoCollaboratorAcceptance struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.repo.collaboratorAcceptance" cborgen:"$type,const=sh.tangled.repo.collaboratorAcceptance"`
	// createdAt: Invite acceptance timestamp
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
}
