// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.countArtifacts

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoCountArtifactsNSID = "sh.tangled.repo.countArtifacts"
)

// RepoCountArtifacts_Output is the output of a sh.tangled.repo.countArtifacts call.
type RepoCountArtifacts_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// RepoCountArtifacts calls the XRPC method "sh.tangled.repo.countArtifacts".
//
// subject: Repo or release identifier whose artifacts to list.
func RepoCountArtifacts(ctx context.Context, c util.LexClient, subject string) (*RepoCountArtifacts_Output, error) {
	var out RepoCountArtifacts_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.countArtifacts", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
