// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.countIssuesBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoCountIssuesByNSID = "sh.tangled.repo.countIssuesBy"
)

// RepoCountIssuesBy_Output is the output of a sh.tangled.repo.countIssuesBy call.
type RepoCountIssuesBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// RepoCountIssuesBy calls the XRPC method "sh.tangled.repo.countIssuesBy".
//
// subject: Actor DID whose issue authorings to list
func RepoCountIssuesBy(ctx context.Context, c util.LexClient, subject string) (*RepoCountIssuesBy_Output, error) {
	var out RepoCountIssuesBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.countIssuesBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
