// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.countRepos

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoCountReposNSID = "sh.tangled.repo.countRepos"
)

// RepoCountRepos_Output is the output of a sh.tangled.repo.countRepos call.
type RepoCountRepos_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// RepoCountRepos calls the XRPC method "sh.tangled.repo.countRepos".
//
// subject: Owner DID whose repo records to list.
func RepoCountRepos(ctx context.Context, c util.LexClient, subject string) (*RepoCountRepos_Output, error) {
	var out RepoCountRepos_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.countRepos", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
