// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.listArtifacts

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoListArtifactsNSID = "sh.tangled.repo.listArtifacts"
)

// RepoListArtifacts_ListItem is a "listItem" in the sh.tangled.repo.listArtifacts schema.
type RepoListArtifacts_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.repo.artifact record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// RepoListArtifacts_Output is the output of a sh.tangled.repo.listArtifacts call.
type RepoListArtifacts_Output struct {
	Cursor *string                       `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*RepoListArtifacts_ListItem `json:"items" cborgen:"items"`
}

// RepoListArtifacts calls the XRPC method "sh.tangled.repo.listArtifacts".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Repo or release identifier whose artifacts to list.
func RepoListArtifacts(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*RepoListArtifacts_Output, error) {
	var out RepoListArtifacts_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.listArtifacts", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
