// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.countCollaboratorsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoCountCollaboratorsByNSID = "sh.tangled.repo.countCollaboratorsBy"
)

// RepoCountCollaboratorsBy_Output is the output of a sh.tangled.repo.countCollaboratorsBy call.
type RepoCountCollaboratorsBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// RepoCountCollaboratorsBy calls the XRPC method "sh.tangled.repo.countCollaboratorsBy".
//
// subject: Actor DID whose collaborator authorings to list.
func RepoCountCollaboratorsBy(ctx context.Context, c util.LexClient, subject string) (*RepoCountCollaboratorsBy_Output, error) {
	var out RepoCountCollaboratorsBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.countCollaboratorsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
