// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.collaborator

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoCollaboratorNSID = "sh.tangled.repo.collaborator"
)

func init() {
	util.RegisterType("sh.tangled.repo.collaborator", &RepoCollaborator{})
} //
// RECORDTYPE: RepoCollaborator
type RepoCollaborator struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.repo.collaborator" cborgen:"$type,const=sh.tangled.repo.collaborator"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	// repo: repo DID to add this user to
	Repo    string `json:"repo" cborgen:"repo"`
	Subject string `json:"subject" cborgen:"subject"`
}
