// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.getIssue

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoGetIssueNSID = "sh.tangled.repo.getIssue"
)

// RepoGetIssue_Output is the output of a sh.tangled.repo.getIssue call.
type RepoGetIssue_Output struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.repo.issue record.
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// RepoGetIssue calls the XRPC method "sh.tangled.repo.getIssue".
//
// issue: AT-URI of the sh.tangled.repo.issue record to fetch.
func RepoGetIssue(ctx context.Context, c util.LexClient, issue string) (*RepoGetIssue_Output, error) {
	var out RepoGetIssue_Output

	params := map[string]interface{}{}
	params["issue"] = issue
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.getIssue", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
