// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.repo.retryWebhookDelivery

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempRepoRetryWebhookDeliveryNSID = "org.tangled.temp.repo.retryWebhookDelivery"
)

// TempRepoRetryWebhookDelivery_Input is the input argument to a org.tangled.temp.repo.retryWebhookDelivery call.
type TempRepoRetryWebhookDelivery_Input struct {
	// deliveryId: UUID of the delivery to retry.
	DeliveryId string `json:"deliveryId" cborgen:"deliveryId"`
	// repoDid: DID of the repository as minted by the knot.
	RepoDid string `json:"repoDid" cborgen:"repoDid"`
	// webhookId: Webhook ID that owns the delivery.
	WebhookId int64 `json:"webhookId" cborgen:"webhookId"`
}

// TempRepoRetryWebhookDelivery calls the XRPC method "org.tangled.temp.repo.retryWebhookDelivery".
func TempRepoRetryWebhookDelivery(ctx context.Context, c util.LexClient, input *TempRepoRetryWebhookDelivery_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "org.tangled.temp.repo.retryWebhookDelivery", nil, input, nil); err != nil {
		return err
	}

	return nil
}
