// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.countPullsBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoCountPullsByNSID = "sh.tangled.repo.countPullsBy"
)

// RepoCountPullsBy_Output is the output of a sh.tangled.repo.countPullsBy call.
type RepoCountPullsBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// RepoCountPullsBy calls the XRPC method "sh.tangled.repo.countPullsBy".
//
// subject: Actor DID whose pull authorings to list
func RepoCountPullsBy(ctx context.Context, c util.LexClient, subject string) (*RepoCountPullsBy_Output, error) {
	var out RepoCountPullsBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.countPullsBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
