// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.repo.updateWebhook

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempRepoUpdateWebhookNSID = "org.tangled.temp.repo.updateWebhook"
)

// TempRepoUpdateWebhook_Input is the input argument to a org.tangled.temp.repo.updateWebhook call.
type TempRepoUpdateWebhook_Input struct {
	Active *bool    `json:"active,omitempty" cborgen:"active,omitempty"`
	Events []string `json:"events,omitempty" cborgen:"events,omitempty"`
	// id: Webhook ID to update.
	Id int64 `json:"id" cborgen:"id"`
	// repoDid: DID of the repository as minted by the knot.
	RepoDid string  `json:"repoDid" cborgen:"repoDid"`
	Secret  *string `json:"secret,omitempty" cborgen:"secret,omitempty"`
	Url     *string `json:"url,omitempty" cborgen:"url,omitempty"`
}

// TempRepoUpdateWebhook calls the XRPC method "org.tangled.temp.repo.updateWebhook".
func TempRepoUpdateWebhook(ctx context.Context, c util.LexClient, input *TempRepoUpdateWebhook_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "org.tangled.temp.repo.updateWebhook", nil, input, nil); err != nil {
		return err
	}

	return nil
}
