// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.site.claimDomain

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempSiteClaimDomainNSID = "org.tangled.temp.site.claimDomain"
)

// TempSiteClaimDomain_Input is the input argument to a org.tangled.temp.site.claimDomain call.
type TempSiteClaimDomain_Input struct {
	// subdomain: Desired subdomain label (lowercase letters, digits, and hyphens; 4–63 characters).
	Subdomain string `json:"subdomain" cborgen:"subdomain"`
}

// TempSiteClaimDomain calls the XRPC method "org.tangled.temp.site.claimDomain".
func TempSiteClaimDomain(ctx context.Context, c util.LexClient, input *TempSiteClaimDomain_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "org.tangled.temp.site.claimDomain", nil, input, nil); err != nil {
		return err
	}

	return nil
}
