// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.site.releaseDomain

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempSiteReleaseDomainNSID = "org.tangled.temp.site.releaseDomain"
)

// TempSiteReleaseDomain_Input is the input argument to a org.tangled.temp.site.releaseDomain call.
type TempSiteReleaseDomain_Input struct {
	// domain: Full domain to release (must match the user's active claim).
	Domain string `json:"domain" cborgen:"domain"`
}

// TempSiteReleaseDomain calls the XRPC method "org.tangled.temp.site.releaseDomain".
func TempSiteReleaseDomain(ctx context.Context, c util.LexClient, input *TempSiteReleaseDomain_Input) error {
	if err := c.LexDo(ctx, util.Procedure, "application/json", "org.tangled.temp.site.releaseDomain", nil, input, nil); err != nil {
		return err
	}

	return nil
}
