// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: org.tangled.temp.site.getDomainClaim

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	TempSiteGetDomainClaimNSID = "org.tangled.temp.site.getDomainClaim"
)

// TempSiteGetDomainClaim_Output is the output of a org.tangled.temp.site.getDomainClaim call.
type TempSiteGetDomainClaim_Output struct {
	// domain: The claimed domain (e.g. 'alice.sites.tangled.sh'). Absent if no active claim.
	Domain *string `json:"domain,omitempty" cborgen:"domain,omitempty"`
}

// TempSiteGetDomainClaim calls the XRPC method "org.tangled.temp.site.getDomainClaim".
func TempSiteGetDomainClaim(ctx context.Context, c util.LexClient) (*TempSiteGetDomainClaim_Output, error) {
	var out TempSiteGetDomainClaim_Output
	if err := c.LexDo(ctx, util.Query, "", "org.tangled.temp.site.getDomainClaim", nil, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
