// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.spindle.countSpindles

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	SpindleCountSpindlesNSID = "sh.tangled.spindle.countSpindles"
)

// SpindleCountSpindles_Output is the output of a sh.tangled.spindle.countSpindles call.
type SpindleCountSpindles_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// SpindleCountSpindles calls the XRPC method "sh.tangled.spindle.countSpindles".
//
// subject: Owner DID whose spindle records to list.
func SpindleCountSpindles(ctx context.Context, c util.LexClient, subject string) (*SpindleCountSpindles_Output, error) {
	var out SpindleCountSpindles_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.spindle.countSpindles", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
