// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.spindle.countMembersBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	SpindleCountMembersByNSID = "sh.tangled.spindle.countMembersBy"
)

// SpindleCountMembersBy_Output is the output of a sh.tangled.spindle.countMembersBy call.
type SpindleCountMembersBy_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// SpindleCountMembersBy calls the XRPC method "sh.tangled.spindle.countMembersBy".
//
// subject: Actor DID whose spindle-member authorings to list.
func SpindleCountMembersBy(ctx context.Context, c util.LexClient, subject string) (*SpindleCountMembersBy_Output, error) {
	var out SpindleCountMembersBy_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.spindle.countMembersBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
