// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.spindle.countMembers

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	SpindleCountMembersNSID = "sh.tangled.spindle.countMembers"
)

// SpindleCountMembers_Output is the output of a sh.tangled.spindle.countMembers call.
type SpindleCountMembers_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// SpindleCountMembers calls the XRPC method "sh.tangled.spindle.countMembers".
//
// subject: Spindle identifier whose member records to list.
func SpindleCountMembers(ctx context.Context, c util.LexClient, subject string) (*SpindleCountMembers_Output, error) {
	var out SpindleCountMembers_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.spindle.countMembers", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
