// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.spindle.listMembersBy

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	SpindleListMembersByNSID = "sh.tangled.spindle.listMembersBy"
)

// SpindleListMembersBy_Output is the output of a sh.tangled.spindle.listMembersBy call.
type SpindleListMembersBy_Output struct {
	Cursor *string                        `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*SpindleListMembers_ListItem `json:"items" cborgen:"items"`
}

// SpindleListMembersBy calls the XRPC method "sh.tangled.spindle.listMembersBy".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Actor DID whose spindle-member authorings to list.
func SpindleListMembersBy(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*SpindleListMembersBy_Output, error) {
	var out SpindleListMembersBy_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.spindle.listMembersBy", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
