// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.string.listStrings

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	StringListStringsNSID = "sh.tangled.string.listStrings"
)

// StringListStrings_ListItem is a "listItem" in the sh.tangled.string.listStrings schema.
type StringListStrings_ListItem struct {
	Cid *string `json:"cid,omitempty" cborgen:"cid,omitempty"`
	Uri string  `json:"uri" cborgen:"uri"`
	// value: Embedded sh.tangled.string record
	Value *util.LexiconTypeDecoder `json:"value" cborgen:"value"`
}

// StringListStrings_Output is the output of a sh.tangled.string.listStrings call.
type StringListStrings_Output struct {
	Cursor *string                       `json:"cursor,omitempty" cborgen:"cursor,omitempty"`
	Items  []*StringListStrings_ListItem `json:"items" cborgen:"items"`
}

// StringListStrings calls the XRPC method "sh.tangled.string.listStrings".
//
// cursor: Pagination cursor
// order: Sort direction by createdAt.
// subject: Scope identifier whose string records to list.
func StringListStrings(ctx context.Context, c util.LexClient, cursor string, limit int64, order string, subject string) (*StringListStrings_Output, error) {
	var out StringListStrings_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	if order != "" {
		params["order"] = order
	}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.string.listStrings", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
