// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.string.countStrings

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	StringCountStringsNSID = "sh.tangled.string.countStrings"
)

// StringCountStrings_Output is the output of a sh.tangled.string.countStrings call.
type StringCountStrings_Output struct {
	// count: Total number of matching records.
	Count int64 `json:"count" cborgen:"count"`
	// distinctAuthors: Number of distinct authors among the matching records.
	DistinctAuthors int64 `json:"distinctAuthors" cborgen:"distinctAuthors"`
}

// StringCountStrings calls the XRPC method "sh.tangled.string.countStrings".
//
// subject: Scope identifier whose string records to list.
func StringCountStrings(ctx context.Context, c util.LexClient, subject string) (*StringCountStrings_Output, error) {
	var out StringCountStrings_Output

	params := map[string]interface{}{}
	params["subject"] = subject
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.string.countStrings", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
