// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.comment

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	CommentNSID = "sh.tangled.comment"
)

func init() {
	util.RegisterType("sh.tangled.comment", &Comment{})
} //
// RECORDTYPE: Comment
type Comment struct {
	LexiconTypeID string   `json:"$type,const=sh.tangled.comment" cborgen:"$type,const=sh.tangled.comment"`
	Body          string   `json:"body" cborgen:"body"`
	CreatedAt     string   `json:"createdAt" cborgen:"createdAt"`
	Mentions      []string `json:"mentions,omitempty" cborgen:"mentions,omitempty"`
	References    []string `json:"references,omitempty" cborgen:"references,omitempty"`
	ReplyTo       *string  `json:"replyTo,omitempty" cborgen:"replyTo,omitempty"`
	Subject       string   `json:"subject" cborgen:"subject"`
}
