// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.git.temp.getDiff

import (
	"bytes"
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GitTempGetDiffNSID = "sh.tangled.git.temp.getDiff"
)

// GitTempGetDiff calls the XRPC method "sh.tangled.git.temp.getDiff".
//
// repo: AT-URI of the repository
// rev1: First revision (commit, branch, or tag)
// rev2: Second revision (commit, branch, or tag)
func GitTempGetDiff(ctx context.Context, c util.LexClient, repo string, rev1 string, rev2 string) ([]byte, error) {
	buf := new(bytes.Buffer)

	params := map[string]interface{}{}
	params["repo"] = repo
	params["rev1"] = rev1
	params["rev2"] = rev2
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.git.temp.getDiff", params, nil, buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
