// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.git.temp.getTag

import (
	"bytes"
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GitTempGetTagNSID = "sh.tangled.git.temp.getTag"
)

// GitTempGetTag calls the XRPC method "sh.tangled.git.temp.getTag".
//
// repo: DID of the repository
// tag: Name of tag, such as v1.3.0
func GitTempGetTag(ctx context.Context, c util.LexClient, repo string, tag string) ([]byte, error) {
	buf := new(bytes.Buffer)

	params := map[string]interface{}{}
	params["repo"] = repo
	params["tag"] = tag
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.git.temp.getTag", params, nil, buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
