// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.git.temp.getHead

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	GitTempGetHeadNSID = "sh.tangled.git.temp.getHead"
)

// GitTempGetHead calls the XRPC method "sh.tangled.git.temp.getHead".
//
// repo: DID of the repository
func GitTempGetHead(ctx context.Context, c util.LexClient, repo string) (*GitTempDefs_Branch, error) {
	var out GitTempDefs_Branch

	params := map[string]interface{}{}
	params["repo"] = repo
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.git.temp.getHead", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
