[package]
name = "knot-ssh"
version = "2.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
knot-types = { workspace = true }
knot-runtime = { workspace = true }
knot-resource = { workspace = true }
knot-git = { workspace = true }
knot-lfs = { workspace = true }
knot-pack = { workspace = true }
knot-index = { workspace = true }
knot-acl = { workspace = true }
knot-atproto = { workspace = true }
knot-cob = { workspace = true }
knot-cobs = { workspace = true }
knot-events = { workspace = true }
knot-maintenance = { workspace = true }
knot-postreceive = { workspace = true }
knot-receive = { workspace = true }
knot-messages = { workspace = true }
tracing = { workspace = true }
russh = "0.61"
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["io-util"] }
futures = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
knot-fixtures = { workspace = true }
tempfile = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
http = { workspace = true }
bytes = { workspace = true }
url = { workspace = true }
russh = "0.61"
tikv-jemallocator = { workspace = true }
tikv-jemalloc-ctl = { workspace = true }
