[package]
name = "knot-edge"
version = "2.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
knot-types = { workspace = true }
axum = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
tower = { workspace = true, features = ["limit", "load-shed"] }
tower-http = { workspace = true, features = ["compression-zstd", "compression-br", "compression-gzip", "timeout", "map-request-body"] }
tower_governor = { workspace = true }
governor = { workspace = true }
http-body = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-rustls = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
rustls-acme = { workspace = true }
x509-parser = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
quinn = { workspace = true }
h3 = { workspace = true }
h3-quinn = { workspace = true }
arc-swap = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
rcgen = { workspace = true }
tempfile = { workspace = true }
