root = "."
tmp_dir = "out"

[build]
cmd = "go build -o out/appview.out cmd/appview/main.go"
bin = "out/appview.out"

include_ext = ["go"]
exclude_dir = ["avatar", "camo", "sites", "indexes", "nix", "tmp", "node_modules"]
stop_on_error = true
