when:
  - event: ["push", "pull_request"]
    branch: master

engine: microvm
image: nixos

dependencies:
  - go
  - gcc

environment:
  CGO_ENABLED: 1

steps:
  - name: patch static dir
    command: |
      mkdir -p appview/pages/static; touch appview/pages/static/x

  - name: build appview
    command: |
      go build -o appview.out ./cmd/appview

  - name: build knot
    command: |
      go build -o knot.out ./cmd/knot

  - name: build spindle
    command: |
      go build -o spindle.out ./cmd/spindle
